// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFzyOQB0BX_6eeMmEUqDrlkgTC51CRXbI',
    appId: '1:603299309981:web:d43b2e85fe8553335d6774',
    messagingSenderId: '603299309981',
    projectId: 'mynotes-thach-new-flutter',
    authDomain: 'mynotes-thach-new-flutter.firebaseapp.com',
    storageBucket: 'mynotes-thach-new-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfnD6IklCyofR0x57e4S-rT4sDxr2zeN8',
    appId: '1:603299309981:android:1283ff7720a70d6f5d6774',
    messagingSenderId: '603299309981',
    projectId: 'mynotes-thach-new-flutter',
    storageBucket: 'mynotes-thach-new-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ8rWnVlrhPisM1xJL1BP8Mao97blJco0',
    appId: '1:603299309981:ios:9f3a3982788e1e235d6774',
    messagingSenderId: '603299309981',
    projectId: 'mynotes-thach-new-flutter',
    storageBucket: 'mynotes-thach-new-flutter.appspot.com',
    iosClientId: '603299309981-cl3hor2fl00c1mn3ptvpe8k0s5v7ono3.apps.googleusercontent.com',
    iosBundleId: 'com.somethinghere.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ8rWnVlrhPisM1xJL1BP8Mao97blJco0',
    appId: '1:603299309981:ios:9f3a3982788e1e235d6774',
    messagingSenderId: '603299309981',
    projectId: 'mynotes-thach-new-flutter',
    storageBucket: 'mynotes-thach-new-flutter.appspot.com',
    iosClientId: '603299309981-cl3hor2fl00c1mn3ptvpe8k0s5v7ono3.apps.googleusercontent.com',
    iosBundleId: 'com.somethinghere.mynotes',
  );
}
